DataFolder = "/mnt/c/Solenix/navidrome/release/linux/data"
MusicFolder = "/mnt/c/Solenix/navidrome/release/linux/music"

# Make logging more verbose
LogLevel = "debug"

# This option will always create an `admin` user with the specified password, so you don't
# have to create a user every time you delete your dev database
DevAutoCreateAdminPassword = "password"
